server:
  port: 8000

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: RESTAURANT-SERVICE
          uri: lb://RESTAURANT-SERVICE
          predicates:
            - Path=/restaurants/**
        - id: FOOD-ITEM-SERVIVCE
          uri: lb://FOOD-ITEM-SERVICE
          predicates:
            - Path=/foodItems/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost